// src/locales/es.ts
const es = {
  translation: {
    // ─── FlowPlanilla nav ────────────────────────────────────
    "Dashboard": "Panel",
    "Users": "Usuarios",
    "Employees": "Empleados",
    "Payrolls": "Nóminas",
    "Sipe": "SIPE",
    "ISR": "ISR",
    "Decimo": "Décimo",
    "Vacaciones": "Vacaciones",
    "Liquidaciones": "Liquidaciones",
    "Legal": "Legal",
    "LegalDecimo": "Legal Décimo",
    "Settings": "Configuración",
    // Groups
    "PRINCIPAL": "PRINCIPAL",
    "NÓMINA": "NÓMINA",
    "REPORTES": "REPORTES",
    "CONFIGURACIÓN": "CONFIGURACIÓN",
    // Common
    "logout": "Cerrar sesión",
    "profile": "Ver perfil",
    "search": "Buscar",
    "notifications": "Notificaciones",
    "no_notifications": "Sin notificaciones pendientes",
    "menu": "Menú",
    "change_language": "Idioma",
    // Chat
    "chat_title": "Asistente FlowPlanilla",
    "chat_placeholder": "Escribe tu pregunta...",
    "chat_welcome": "Hola, soy tu asistente de FlowPlanilla. ¿En qué puedo ayudarte?",
    "chat_send": "Enviar",
    "chat_thinking": "Pensando...",
    // ─── Legacy (maritime) ────────────────────────────────────
    "Ayudanos a Ayudarte": "Help Us Help You",
    "Que informacion necesitas?": "What information do you need?",
    "Cursos": "Courses",
    "Tramite de Licencia": "License Procedure",
    "Liberia COC": "Liberia COC",

    // Header
    "Cotización de Cursos": "Cotización de Cursos",
    "Selecciona tu nacionalidad, gobierno/institución y los cursos marítimos de tu interés para obtener una cotización": "Selecciona tu nacionalidad, gobierno/institución y los cursos marítimos de tu interés para obtener una cotización",
    
    // Form Section: Personal Info
    "Información Personal": "Información Personal",
    "Completa tus datos para generar la cotización": "Completa tus datos para generar la cotización",
    "Nombre": "Nombre",
    "Tu nombre": "Tu nombre",
    "Apellido": "Apellido",
    "Tu apellido": "Tu apellido",
    "Cédula o Pasaporte": "Cédula o Pasaporte",
    "Número de documento": "Número de documento",
    "Nacionalidad": "Nacionalidad",
    "Selecciona tu nacionalidad": "Selecciona tu nacionalidad",
    "Determina si usas precios para panameños o extranjeros": "Determina si usas precios para panameños o extranjeros",
    "✅ Precios panameños": "✅ Precios panameños",
    "🌍 Precios extranjeros": "🌍 Precios extranjeros",
    "Correo Electrónico": "Correo Electrónico",
    "tu@email.com": "tu@email.com",
    "Teléfono": "Teléfono",
    "+1 (123) 456-7890": "+1 (123) 456-7890",

    // Form Section: Course Selection
    "Gobierno/Institución": "Gobierno/Institución",
    "Selecciona el gobierno/institución": "Selecciona el gobierno/institución",
    "Se aplicará un recargo del {{surcharge}}% sobre el precio base": "Se aplicará un recargo del {{surcharge}}% sobre el precio base",
    "Sin recargo adicional": "Sin recargo adicional",
    "Cursos Marítimos Nuevos": "Cursos Marítimos Nuevos",
    "(Busca por nombre o abreviación)": "(Busca por nombre o abreviación)",
    "Renovación de Cursos": "Renovación de Cursos",
    "(Solo cursos que permiten renovación)": "(Solo cursos que permiten renovación)",

    // Form Section: Verification & Submission
    "Verificación CAPTCHA": "Verificación CAPTCHA",
    "Acepto los <1>términos y condiciones</1> y la <2>política de privacidad</2>": "Acepto los <1>términos y condiciones</1> y la <2>política de privacidad</2>",
    "Generando cotización...": "Generando cotización...",
    "Generar Cotización": "Generar Cotización",
    
    // Alerts
    "Por favor, selecciona un gobierno/institución.": "Por favor, selecciona un gobierno/institución.",
    "Por favor, selecciona tu nacionalidad.": "Por favor, selecciona tu nacionalidad.",
    "Por favor, selecciona al menos un curso nuevo o de renovación.": "Por favor, selecciona al menos un curso nuevo o de renovación.",
    "Error: Hay cursos seleccionados tanto como nuevos como para renovación. Por favor, revisa tu selección.": "Error: Hay cursos seleccionados tanto como nuevos como para renovación. Por favor, revisa tu selección.",
    "Por favor, verifica el captcha antes de continuar.": "Por favor, verifica el captcha antes de continuar.",
    "Debes aceptar los términos y condiciones para continuar.": "Debes aceptar los términos y condiciones para continuar.",
    "Hubo un error al enviar tu cotización": "Hubo un error al enviar tu cotización",

    // Confirmation View
    "¡Cotización Generada!": "¡Cotización Generada!",
    "Tu cotización ha sido generada exitosamente": "Tu cotización ha sido generada exitosamente",
    "Cotización Confirmada": "Cotización Confirmada",
    "Resumen de tu cotización de cursos marítimos": "Resumen de tu cotización de cursos marítimos",
    "Costo Total": "Costo Total",
    "Nuevos: ${{newCoursesTotal}}": "Nuevos: ${{newCoursesTotal}}",
    "Renovaciones: ${{renewalCoursesTotal}}": "Renovaciones: ${{renewalCoursesTotal}}",
    "Cursos Nuevos:": "Cursos Nuevos:",
    "Renovaciones:": "Renovaciones:",
    "Código: {{abbr}}": "Código: {{abbr}}",
    "(Renovación)": "(Renovación)",
    "Datos del estudiante:": "Datos del estudiante:",
    "Nombre completo:": "Nombre completo:",
    "Documento:": "Documento:",
    "Email:": "Email:",
    "Gobierno/Institución:": "Gobierno/Institución:",
    "Nueva Cotización": "Nueva Cotización",
    "Descargar PDF": "Descargar PDF",
    "Verificar": "Verificar",
    "Ingresa el Código": "Ingresa el Código",
    "Código incorrecto. Intenta de nuevo": "Código incorrecto. Intenta de nuevo",
    "¡Verificación exitosa!": "¡Verificación exitosa!",
    "Por favor, revisa tu correo electrónico para ver la cotización completa." : "Please check your email to see the full quote.",
    "Solicitud de Licencia": "License Application",
    "Completa el formulario para recibir información personalizada": "Complete the form to receive personalized information",
    "Información sobre las licencias": "License Information ",
    "En poco tiempo estaremos contactándole.": "We will be in touch with you shortly.",
    "¡Gracias por su interés!": "Thank you for your interest!",
    "Haga clic para subir": "Click for Upload",
    "o arrastre aquí": "or drag here",
    "Enviar": "Submit",
    "Escribe aquí tu consulta sobre las licencias que necesitas...": "Write your query here about the licenses you need...",
    "No eres tú, somos nosotros": "It's not you, it's us",
    "Volver a la página de inicio": "Go to home page",
    "Estoy de acuerdo que estos cursos son 100% presenciales": "I agree that these courses are 100% in-person",
  }
};

export default es;